### ISSUE TITLE
not working with ruby 2.7.0

### ISSUE THREAD

**Issue by rebebop** [18Months/themoviedb-api#20]
Hi,
The current version is not working with `ruby 2.7.0` and it's giving the following error:
```
undefined method `new_ostruct_member'
```

Because the `new_ostruct_member` was removed from `2.7.0`.

**Comment by railssmith** [comment]
i am also getting the same error

**Comment by yurgon** [comment]
same error

**Comment by robby1066** [comment]
I'm getting it too after upgrading to Ruby 2.7

**Comment by drukepple** [comment]
I was able to fix this (I believe, so far) by editing `new_ostruct_member` on https://github.com/18Months/themoviedb-api/blob/master/lib/tmdb/struct.rb#L11 to `new_ostruct_member!`. I just did this in my local gem installation, good enough for now. I'm not sure if there are other cases where this change needs to be made.

If I read the docs correctly, the `new_ostruct_member` method was effectively "renamed" to `new_ostruct_member!`.

I will try to create a PR today or tomorrow.

**Comment by zvallarino** [comment]
> I was able to fix this (I believe, so far) by editing `new_ostruct_member` on https://github.com/18Months/themoviedb-api/blob/master/lib/tmdb/struct.rb#L11 to `new_ostruct_member!`. I just did this in my local gem installation, good enough for now. I'm not sure if there are other cases where this change needs to be made.
> 
> If I read the docs correctly, the `new_ostruct_member` method was effectively "renamed" to `new_ostruct_member!`.
> 
> I will try to create a PR today or tomorrow.

In this fix how did you use your local gem file? I cloned mine down. Then used a gem package maker in new directory. Rake installed that. That worked, so I thought I should clone my project into that folder so I have access to the gem but Whenever I try to run my normal bundle install, it won’t let me bundle install after. It says invalid gem and points to my gem. The only thing I did was follow your guidelines and added a ! to the thing in the lib folder.


Any ideas on how I should solve this? Ty for any help.

**Comment by jerryclinesmith** [comment]
@drukepple's fix did load without error, but I had to use the hash syntax (movie[:id]) to read attributes instead of dot syntax (movie.id).  Below is the change I made, which allowed both to work:
```
    def initialize(data=nil)
      @table = {}

      if data
        data.each do |k,v|
          set_ostruct_member_value! k, analyze_value(v)
        end
      end
    end
```

**Comment by alejandroperea** [comment]
I've opened a PR trying to do a general update of the gem: https://github.com/18Months/themoviedb-api/pull/24
